### ISSUE TITLE
Lowering rating causes a 6th star to appear

### ISSUE THREAD

**Issue by bialesdaniel** [rajeshwarpatlolla/ionic-ratings#11]
Hi,

Thanks for this great component. I am running into an issue where I have implemented it and am testing it on an IOS simulator and when I select a high rating and then try to change it to be lower then the UI flashes and a 6th star appears momentarily below the other stars.

Additionally if 3 stars are selected and I click the 3rd star, the UI will flash, the 6th star will flash and disappear and only 1 star will be selected

**Comment by rajeshwarpatlolla** [comment]
Please take a look at the demo. I tried to re produce this issue. But it's not reproducing. Let me know if it can be reproduced again.
