### ISSUE TITLE
flicker on safari when clicked

### ISSUE THREAD

**Issue by cristiandan** [rajeshwarpatlolla/ionic-ratings#13]
The stars flicker on both iOS safari and OS x safari when I click them.
I recorded my screen so you can see.
[Archive.zip](https://github.com/rajeshwarpatlolla/ionic-ratings/files/203003/Archive.zip)

**Comment by alunatam** [comment]
@cristiandan where you able to solve this issue? Happens exactly the same for me. I was checking this alternate lib http://codepen.io/calendee/pen/zxygJe. This one works fine.

**Comment by cristiandan** [comment]
@alunatam thanks for sharing, 
I couldn't find a way to fix this one though.

**Comment by preetam-yadav** [comment]
I have resolved this issue by changing ng-show to ng-if.

in ionic-rating.js 
Change in directive function : ng-show to ng-if.

ng-show already inserted a element in dom and then show on basis of condition .so use ng-if it insert at run time on basis of condition so flicker issue resolved.
