### ISSUE TITLE
Problem with Android 4.2.2

### ISSUE THREAD

**Issue by benessuti** [rajeshwarpatlolla/ionic-ratings#19]
Hi,

In old versions, like android 4.2.2, this plugin does not work correctly. The stars seems to be disabled, like in the status "read only". 

Do you know why?

Thank you.

**Comment by rajeshwarpatlolla** [comment]
Yes, this plugin works fine from android 4.4.4 kitkat. You need to override some css in order to work with the older versions. Please refer to the css classes i mentioned in the documentation.
