### ISSUE TITLE
Show Half star 

### ISSUE THREAD

**Issue by monsif** [rajeshwarpatlolla/ionic-ratings#23]
Hi, i am trying to show half star rating like 2.5 , 1.5 ... how can i manage to do that ? i am getting 6 stars instead.
thanks

**Comment by ykarthikreddy18** [comment]
@monsif ..Did you got it working? .. I'm also having same problem..

**Comment by monsif** [comment]
@ykarthikreddy18 no i finished by giving up on it.

**Comment by monsif** [comment]
@ykarthikreddy18 i now use this plugin https://github.com/andrucz/ionic2-rating which is matching all my needs.

**Comment by rajeshwarpatlolla** [comment]
There is no option as of now.
