### ISSUE TITLE
Can't show dynamically multiple ratings

### ISSUE THREAD

**Issue by tkalpit** [rajeshwarpatlolla/ionic-ratings#24]
first problem : I have this loop in html file 
"<div ng-repeat="(key,comm) in comments">
 <div class = "item item-thumbnail-left">
	<ionic-ratings style = 'text-align:left' ratingsobj='ratingsObj'  index=$index></ionic-ratings>
</div>
</div>"

In above code first of all what is index attribute for and i can't assign key to index attribute tell me how to assign value to index attribute. 

Second Problem:  below code in my js file code

$scope.ratingsObj = {
		iconOn : 'ion-ios-star',
		iconOff : 'ion-ios-star-outline',
		iconOnColor: 'rgb(200, 200, 100)',
		iconOffColor:  'rgb(200, 100, 100)',
		rating:  0,
		minRating:0,
		readOnly:true,
		callback: function(rating,index) {
		  $scope.ratingsCall(rating,index);
		}
	};
$scope.ratingsCall = function(rating,index) {
   starRating = rating;
console.log(' rating is : ', index);
 };
call back function not called in case of readOnly?
and how to assign rating to different values like for 1st comment there are 3 star and for second there 4 star so how to do this ??

**Comment by tkalpit** [comment]
<div ng-repeat="(key,comm) in comments">
 <div class = "item item-thumbnail-left">
	<ionic-ratings style = 'text-align:left' ratingsobj='ratingsObj'  index=$index></ionic-ratings>
</div>
</div>
html file code

**Comment by rajeshwarpatlolla** [comment]
You need to have as many instances as u have comments, so that each and every comment can have different ratings.

**Comment by tkalpit** [comment]
@rajeshwarpatlolla Thanks for reply. I have one more problem all comments are dynamic and they are printed in loop. please go through below code.

$scope.comments.forEach(function(element,key) {
    $scope.ratingObj["key" + key] = {
    iconOn : 'ion-ios-star',
    iconOff : 'ion-ios-star-outline',
    iconOnColor: 'rgb(200, 200, 100)',
    iconOffColor:  'rgb(200, 100, 100)',
    rating:  0,
    minRating:0,
    readOnly:true,
    callback: function(rating,index) {
	$scope.ratingsCall(rating,index);
   }
};
});
this code in controller how to concat key to object name it will give me error "Cannot set property '0' of undefined"
