### ISSUE TITLE
change rating value programmatically

### ISSUE THREAD

**Issue by ffabreti** [rajeshwarpatlolla/ionic-ratings#4]
Hi, thanks for your code.
Is there any way of altering the rating programmatically?
That would be a great feature.
Thanks.

**Comment by rajeshwarpatlolla** [comment]
For now there is no such feature implemented. The only way will be altering from the UI.

**Comment by meletakis** [comment]
Hello rajeshwarpatlolla,
great work.
I want to ask you if there is any way to initialize the rating value?

**Comment by rajeshwarpatlolla** [comment]
The initialization of the rating can be done as mentioned [here](https://github.com/rajeshwarpatlolla/ionic-ratings#4-in-your-controller-please-define-the-object-which-you-need-to-pass-to-the-directive)

**Comment by ahmedshabib** [comment]
In the directive code just put in the following lines :)

```
scope.$watch("ratingsObj.rating", function(value) {

          scope.rating = scope.ratingsObj.rating;

          scope.ratingsClicked(scope.rating);

        });

```
