### ISSUE TITLE
Bugs in default value for attribute 'rating' and 'minRating'

### ISSUE THREAD

**Issue by l1nknyto** [rajeshwarpatlolla/ionic-ratings#5]
Hi Rajeshwar,

Nice works for the ionic-ratings.
When i try your component, i can't set 0 for rating or minRating.
I have try your codepen and same issue still happening.
Here's what i try in codepen and its work:

```
    scope.rating = (typeof scope.ratingsObj.rating !== 'undefined') ? scope.ratingsObj.rating : 0;
    scope.minRating = (typeof scope.ratingsObj.minRating !== 'undefined') ? scope.ratingsObj.minRating : 0;
```

Thanks

**Comment by rajeshwarpatlolla** [comment]
Thanks for sharing this with me. I will add this snippet in the next release.

**Comment by hm4rk** [comment]
Thank you, l1nknyto!

**Comment by dmoczydlowski** [comment]
@rajeshwarpatlolla do you have any idea how to fix it ?

**Comment by rajeshwarpatlolla** [comment]
Now it also supports zero rating. Please check [codepen Demo](http://codepen.io/rajeshwarpatlolla/pen/vOQJej) or [plunker Demo](http://plnkr.co/edit/YjpF7hqeMK0HGjeklc6z?p=preview)
