### ISSUE TITLE
Alignment

### ISSUE THREAD

**Issue by c0rv4x** [rajeshwarpatlolla/ionic-ratings#6]
Hi! Could you tell me how can i make an input with ratings like this: 

``` HTML
  <div class="item item-input">
      <span class="input-label">Satisfaction</span>
      <ionic-ratings ratingsobj="satisfactionObject"></ionic-ratings>
  </div>
```

But align ratings to the right of the field?  

P.S.

``` CSS
text-align: right;
```

did not work

**Comment by rajeshwarpatlolla** [comment]
Did you had a look at the demo @ http://codepen.io/rajeshwarpatlolla/pen/vOQJej

**Comment by c0rv4x** [comment]
Thanks for note. Yes, i have checked that out, but there is no point on how to align whole 'ionic-ratings' object to a certaing place in the current div. Actually solved this problem like this: 

``` HTML
      <div class="item item-input">
        <div class="col">
          <span class="input-label">Satisfaction</span>
        </div>
        <div class="col">
          <ionic-ratings style="text-align:right; padding-right: 44px;" ratingsobj="satisfactionObject"></ionic-ratings>
        </div>
      </div>
```

So 

``` CSS
text-align: right;
```

actually worked. No idea what made it work, but now it does. Important to note, that 

``` HTML
<div> 
```

should be used, not

``` HTML
<label>
```

 And for alignment inside div i used grid from ionic framework

**Comment by rajeshwarpatlolla** [comment]
Thanks for sharing this information @iad42.
