### ISSUE TITLE
Rating not clickable on HTC and Samsung

### ISSUE THREAD

**Issue by ghchia** [rajeshwarpatlolla/ionic-ratings#8]
Hi, 

The rating didn't work on HTC One (Android 4.3 - API 18) and Samsung (GT-19305 Android 4.3). The ng-click function (scope.ratingsClicked) is not invoked when the rating is clicked. 

The rating did work on Chrome and Samsung Galaxy Android 4.4.4. 

Do you have any thoughts on why this is happening? 

Regards,
Jennifer

**Comment by rajeshwarpatlolla** [comment]
The minimum support is from android 4.4 version onwards. So you can test it from the android v4.4 onwards.
