### ISSUE TITLE
rating 0 not working

### ISSUE THREAD

**Issue by comapedrosa** [rajeshwarpatlolla/ionic-ratings#9]
Hello! I've been playing with this plugin for a while but it seems that if you set `rating:0` on the  `$scope.ratingsObject`it isn't working: Here you have the example that I've tried:

```
      $scope.ratingsObject = {
        iconOn: 'ion-ios-star',    //Optional
        iconOff: 'ion-ios-star-outline',   //Optional
        iconOnColor: 'rgb(200, 200, 100)',  //Optional
        iconOffColor:  'rgb(200, 100, 100)',    //Optional
        rating:  0, //Optional
        minRating:0,    //Optional
        readOnly: true, //Optional
        callback: function(rating) {    //Mandatory
          $scope.ratingsCallback(rating);
        }
      };
```

And here a fork of the codepen demo with the values set to 0 as in the code above.
http://codepen.io/anon/pen/XXRMrN

**Comment by dmoczydlowski** [comment]
Any idea what to do with it ? 

@comapedrosa  ?

**Comment by rajeshwarpatlolla** [comment]
Check this [codepen](http://codepen.io/rajeshwarpatlolla/pen/WryYQy). Now it also supports zero rating.
